id: I7C886ECB
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:27.472604
last_modified: 2023-01-04 11:31:27.472615
source_metadata:
  collections:
  - Chögyal Pakpa Lodrö Gyaltsen
  - Works of Tibetan Masters
bases:
  3FBB:
    title: Thirty-Seven Point Maṇḍala Offering
    base_file: 3FBB.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
